<a href="https://colab.research.google.com/github/carlopaladino/BigData/blob/main/ProgettoBigData_intermedio1.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [ ]:
from google.colab import drive
drive.mount('/content/drive')

Mounted at /content/drive


#Data Semantics

In [ ]:
import pandas as pd
import matplotlib.pyplot as plt
import numpy as np 
import seaborn as sns
import warnings
warnings.filterwarnings('ignore')
from sklearn.model_selection import train_test_split
from sklearn.preprocessing import PowerTransformer
from imblearn.over_sampling import SMOTE
from sklearn.linear_model import LogisticRegression
from sklearn.ensemble import RandomForestClassifier
import xgboost as xgb
from sklearn.model_selection import GridSearchCV
from sklearn.metrics import confusion_matrix, roc_auc_score, roc_curve, auc, classification_report, plot_confusion_matrix
import pickle

In [18]:
df = pd.read_csv("/content/drive/MyDrive/BigData/data_python_for_data_science/transaction_dataset.csv", index_col = [0])
df.drop(columns='Index', inplace=True) #delete this column
df.head()

                                      Address  ...   ERC20_most_rec_token_type
0  0x00009277775ac7d0d59eaad8fee3d10ac6c805e8  ...                   Numeraire
1  0x0002b44ddb1476db43c868bd494422ee4c136fed  ...              Livepeer Token
2  0x0002bda54cb772d040f779e88eb453cac0daa244  ...                       XENON
3  0x00038e6ba2fd5c09aedb96697c8d7b8fa6632e5e  ...                       XENON
4  0x00062d1dd1afb6fb02540ddad9cdebfe568e0d89  ...                         EOS

[5 rows x 49 columns]

In [31]:
print(df.shape) #number of rows and columns
df.sample(5)

(9841, 49)

                                         Address  ...   ERC20_most_rec_token_type
4480  0x770cfd57613402f67ae0c8d5a7ef15bdc72427b9  ...                     OmiseGO
4387  0x746c2d132e642e5a1ea249eb88ffbf8577e054f2  ...                  Bitcoineum
6388  0xaa3f81703c696e216b36f3bb089071ae4b0d824a  ...                           0
8209  0x3dcf0aa2d91376f974678f509f2e69c88467089c  ...       Blockwell say NOTSAFU
7187  0xc0c3d1b7df0b6153e291c3a6a0fbab31c5213dee  ...                 ZMINE Token

[5 rows x 49 columns]

In [29]:
print(df.columns) #each record is described by these variables:

Index(['Address', 'FLAG', 'Avg min between sent tnx',
       'Avg min between received tnx',
       'Time Diff between first and last (Mins)', 'Sent tnx', 'Received Tnx',
       'Number of Created Contracts', 'Unique Received From Addresses',
       'Unique Sent To Addresses', 'min value received', 'max value received ',
       'avg val received', 'min val sent', 'max val sent', 'avg val sent',
       'min value sent to contract', 'max val sent to contract',
       'avg value sent to contract',
       'total transactions (including tnx to create contract',
       'total Ether sent', 'total ether received',
       'total ether sent contracts', 'total ether balance',
       ' Total ERC20 tnxs', ' ERC20 total Ether received',
       ' ERC20 total ether sent', ' ERC20 total Ether sent contract',
       ' ERC20 uniq sent addr', ' ERC20 uniq rec addr',
       ' ERC20 uniq sent addr.1', ' ERC20 uniq rec contract addr',
       ' ERC20 avg time between sent tnx', ' ERC20 avg time between rec tnx',
       ' ERC20 avg time between rec 2 tnx',
       ' ERC20 avg time between contract tnx', ' ERC20 min val rec',
       ' ERC20 max val rec', ' ERC20 avg val rec', ' ERC20 min val sent',
       ' ERC20 max val sent', ' ERC20 avg val sent',
       ' ERC20 min val sent contract', ' ERC20 max val sent contract',
       ' ERC20 avg val sent contract', ' ERC20 uniq sent token name',
       ' ERC20 uniq rec token name', ' ERC20 most sent token type',
       ' ERC20_most_rec_token_type'],
      dtype='object')

#Data Quality Evaluation

In [26]:
df.info() #informations about the index dtype and columns, non-null values and memory usage

<class 'pandas.core.frame.DataFrame'>
Int64Index: 9841 entries, 0 to 9840
Data columns (total 49 columns):
 #   Column                                                Non-Null Count  Dtype
---  ------                                                --------------  -----
 0   Address                                               9841 non-null   object
 1   FLAG                                                  9841 non-null   int64
 2   Avg min between sent tnx                              9841 non-null   float64
 3   Avg min between received tnx                          9841 non-null   float64
 4   Time Diff between first and last (Mins)               9841 non-null   float64
 5   Sent tnx                                              9841 non-null   int64
 6   Received Tnx                                          9841 non-null   int64
 7   Number of Created Contracts                           9841 non-null   int64
 8   Unique Received From Addresses                        9841 non-null   int64
 9   Unique Sent To Addresses                              9841 non-null   int64
 10  min value received                                    9841 non-null   float64
 11  max value received                                    9841 non-null   float64
 12  avg val received                                      9841 non-null   float64
 13  min val sent                                          9841 non-null   float64
 14  max val sent                                          9841 non-null   float64
 15  avg val sent                                          9841 non-null   float64
 16  min value sent to contract                            9841 non-null   float64
 17  max val sent to contract                              9841 non-null   float64
 18  avg value sent to contract                            9841 non-null   float64
 19  total transactions (including tnx to create contract  9841 non-null   int64
 20  total Ether sent                                      9841 non-null   float64
 21  total ether received                                  9841 non-null   float64
 22  total ether sent contracts                            9841 non-null   float64
 23  total ether balance                                   9841 non-null   float64
 24   Total ERC20 tnxs                                     9012 non-null   float64
 25   ERC20 total Ether received                           9012 non-null   float64
 26   ERC20 total ether sent                               9012 non-null   float64
 27   ERC20 total Ether sent contract                      9012 non-null   float64
 28   ERC20 uniq sent addr                                 9012 non-null   float64
 29   ERC20 uniq rec addr                                  9012 non-null   float64
 30   ERC20 uniq sent addr.1                               9012 non-null   float64
 31   ERC20 uniq rec contract addr                         9012 non-null   float64
 32   ERC20 avg time between sent tnx                      9012 non-null   float64
 33   ERC20 avg time between rec tnx                       9012 non-null   float64
 34   ERC20 avg time between rec 2 tnx                     9012 non-null   float64
 35   ERC20 avg time between contract tnx                  9012 non-null   float64
 36   ERC20 min val rec                                    9012 non-null   float64
 37   ERC20 max val rec                                    9012 non-null   float64
 38   ERC20 avg val rec                                    9012 non-null   float64
 39   ERC20 min val sent                                   9012 non-null   float64
 40   ERC20 max val sent                                   9012 non-null   float64
 41   ERC20 avg val sent                                   9012 non-null   float64
 42   ERC20 min val sent contract                          9012 non-null   float64
 43   ERC20 max val sent contract                          9012 non-null   float64
 44   ERC20 avg val sent contract                          9012 non-null   float64
 45   ERC20 uniq sent token name                           9012 non-null   float64
 46   ERC20 uniq rec token name                            9012 non-null   float64
 47   ERC20 most sent token type                           9000 non-null   object
 48   ERC20_most_rec_token_type                            8990 non-null   object
dtypes: float64(39), int64(7), object(3)
memory usage: 3.8+ MB

In [20]:
df.describe() #Used to view some basic statistical details like percentile, mean, std etc

              FLAG  ...   ERC20 uniq rec token name
count  9841.000000  ...                 9012.000000
mean      0.221421  ...                    4.826676
std       0.415224  ...                   16.678607
min       0.000000  ...                    0.000000
25%       0.000000  ...                    0.000000
50%       0.000000  ...                    1.000000
75%       0.000000  ...                    2.000000
max       1.000000  ...                  737.000000

[8 rows x 46 columns]

In [34]:
df['Address'].unique()

array(['0x00009277775ac7d0d59eaad8fee3d10ac6c805e8',
       '0x0002b44ddb1476db43c868bd494422ee4c136fed',
       '0x0002bda54cb772d040f779e88eb453cac0daa244', ...,
       '0xff8e6af02d41a576a0c82f7835535193e1a6bccc',
       '0xffde23396d57e10abf58bd929bb1e856c7718218',
       '0xd624d046edbdef805c5e4140dce5fb5ec1b39a3c'], dtype=object)

In [35]:
df['FLAG'].unique()

array([0, 1])